# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Sujay S Kumar
tagline:          'Technical Architect and Lead - Natural Language Processing (NLP)'
description:      'Building natural language, speech and conversational interfaces at <a href="http://hypersonix.ai">hypersonix.ai</a>'
url:              https://sujayskumar.com
baseurl:          /

author:
  name:           'Sujay S Kumar'
  url:            https://sujayskumar.com

# Gems
plugins: [jekyll-paginate, jekyll-gist, jekyll-seo-tag, jekyll-sitemap]
paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/SujaySKumar

# Google Analytics
google_analytics: UA-149440204-1
