# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Sujay S Kumar
tagline:          'Lead Machine Learning Engineer (NLP)'
description:      'Building speech and conversational interfaces at <a href="http://hypersonix.ai">hypersonix.ai</a>'
url:              http://sujayskumar.com
baseurl:          /

author:
  name:           'Sujay S Kumar'
  url:            http://sujayskumar.com

# Gems
plugins: [jekyll-paginate, jekyll-gist]
paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/SujaySKumar
